CREATE TABLE Parking (
  id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  updatedAt DATETIME NULL
);

CREATE TABLE Vehicle (
  id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  plate VARCHAR(255) NOT NULL,
  time BIGINT NOT NULL,
  parking VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  updatedAt DATETIME NULL,
  state TINYINT NOT NULL  DEFAULT(0) CHECK (state IN (0,1)),
  parking_id INT NOT NULL,
  CONSTRAINT FK_CarParking_Parking FOREIGN KEY (parking_id) REFERENCES Parking(id)
);


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_LUGARES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_LUGARES](
	[ID_LUGAR] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](30) NULL,
	[LATITUD] [float] NULL,
	[LONGITUD] [float] NULL,
	[TARIFA] [nvarchar](50) NULL,
	[HORARIO] [nvarchar](50) NULL,
	[ESTADO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_LUGARES] PRIMARY KEY CLUSTERED 
(
	[ID_LUGAR] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_USUARIOS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_USUARIOS](
	[ID_USUARIO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[RUT] [nvarchar](18) NULL,
	[DV] [nvarchar](1) NULL,
	[NOMBRES] [nvarchar](30) NULL,
	[APELLIDOS] [nvarchar](40) NULL,
	[TELEFONO] [nvarchar](40) NULL,
	[CLAVE_ACCESO] [nvarchar](8) NULL,
	[MAIL] [nvarchar](20) NULL,
	[ESTADO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_CELULARES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_CELULARES](
	[ID_CELULAR] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[FECHA_HORA_ACTIVACION] [nvarchar](20) NULL,
	[IMEI] [nvarchar](20) NULL,
	[SERIE] [nvarchar](20) NULL,
	[ESTADO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_CELULARES] PRIMARY KEY CLUSTERED 
(
	[ID_CELULAR] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Parking]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Parking](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[location] [varchar](255) NULL,
	[createdAt] [datetime] NOT NULL DEFAULT (getdate()),
	[updatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_TRANSACCIONES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_TRANSACCIONES](
	[ID_TRANSACCION] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_TRANSACCION_ORIGEN] [numeric](18, 0) NULL,
	[FECHANUM_ENTRADA] [numeric](18, 0) NULL,
	[FECHANUM_SALIDA] [numeric](18, 0) NULL,
	[HORA_ENTRADA] [nvarchar](8) NULL,
	[HORA_SALIDA] [nvarchar](8) NULL,
	[MINUTOS_ESTADIA] [numeric](18, 0) NULL,
	[MONTO_PAGADO] [numeric](18, 0) NULL,
	[ID_TARJETA] [numeric](18, 0) NULL,
	[ID_PLACA] [numeric](18, 0) NULL,
	[ID_CELULAR] [numeric](18, 0) NULL,
	[FECHAHORA_TRANSACCION_CREADA] [nvarchar](20) NULL,
	[ID_USUARIO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_TRANSACCIONES] PRIMARY KEY CLUSTERED 
(
	[ID_TRANSACCION] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_REGISTRO_USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_REGISTRO_USUARIO](
	[ID_REGISTRO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [numeric](18, 0) NULL,
	[ID_CELULAR] [numeric](18, 0) NULL,
	[ID_PLACA] [numeric](18, 0) NULL,
	[ID_TARJETA] [numeric](18, 0) NULL,
	[ESTADO] [numeric](18, 0) NULL,
	[FECHANUM] [numeric](18, 0) NULL,
	[HORA] [nvarchar](5) NULL,
 CONSTRAINT [PK_TBL_REGISTRO_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_REGISTRO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_TARJETA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_TARJETA](
	[ID_TARJETA] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NUMERO_TARJETA] [numeric](18, 0) NULL,
	[MES_VCTO] [numeric](18, 0) NULL,
	[ANO_VCTO] [numeric](18, 0) NULL,
	[CVV] [numeric](18, 0) NULL,
	[TIPO] [numeric](18, 0) NULL,
	[DEFAULT_TARJETA] [numeric](18, 0) NULL,
	[ID_USUARIO] [numeric](18, 0) NULL,
	[FECHA_HORA_CREADO] [nvarchar](20) NULL,
	[ESTADO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_TARJETA] PRIMARY KEY CLUSTERED 
(
	[ID_TARJETA] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_SESIONES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_SESIONES](
	[ID_SESION] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[KEY_SESSION] [numeric](18, 0) NULL,
	[ID_USUARIO] [numeric](18, 0) NULL,
	[FECHA_HORA_ULTIMO_ACCESO] [nvarchar](20) NULL,
	[FECHA_HORA_CREADO] [nvarchar](20) NULL,
	[ESTADO] [numeric](18, 0) NULL,
	[ID_CELULAR] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_SESIONES] PRIMARY KEY CLUSTERED 
(
	[ID_SESION] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TBL_PLACA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TBL_PLACA](
	[ID_PLACA] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[PLACA] [nvarchar](6) NULL,
	[PLACA_DEFAULT] [numeric](18, 0) NULL,
	[ID_USUARIO] [numeric](18, 0) NULL,
	[FECHA_HORA_CREADO] [nvarchar](20) NULL,
	[ESTADO] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_PLACA] PRIMARY KEY CLUSTERED 
(
	[ID_PLACA] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Vehicle]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Vehicle](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[plate] [varchar](255) NOT NULL,
	[time] [bigint] NOT NULL,
	[parking] [varchar](255) NOT NULL,
	[createdAt] [datetime] NOT NULL DEFAULT (getdate()),
	[updatedAt] [datetime] NULL,
	[state] [tinyint] NOT NULL DEFAULT ((0)),
	[parking_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_TRAN_REFERENCE_TBL_CELU]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_TRANSACCIONES]'))
ALTER TABLE [dbo].[TBL_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_TRAN_REFERENCE_TBL_CELU] FOREIGN KEY([ID_CELULAR])
REFERENCES [dbo].[TBL_CELULARES] ([ID_CELULAR])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_TRAN_REFERENCE_TBL_PLAC]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_TRANSACCIONES]'))
ALTER TABLE [dbo].[TBL_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_TRAN_REFERENCE_TBL_PLAC] FOREIGN KEY([ID_PLACA])
REFERENCES [dbo].[TBL_PLACA] ([ID_PLACA])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_TRAN_REFERENCE_TBL_TARJ]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_TRANSACCIONES]'))
ALTER TABLE [dbo].[TBL_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_TRAN_REFERENCE_TBL_TARJ] FOREIGN KEY([ID_TARJETA])
REFERENCES [dbo].[TBL_TARJETA] ([ID_TARJETA])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_TRAN_REFERENCE_TBL_USUA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_TRANSACCIONES]'))
ALTER TABLE [dbo].[TBL_TRANSACCIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_TRAN_REFERENCE_TBL_USUA] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TBL_USUARIOS] ([ID_USUARIO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_REGI_REFERENCE_TBL_CELU]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_REGISTRO_USUARIO]'))
ALTER TABLE [dbo].[TBL_REGISTRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_REGI_REFERENCE_TBL_CELU] FOREIGN KEY([ID_CELULAR])
REFERENCES [dbo].[TBL_CELULARES] ([ID_CELULAR])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_REGI_REFERENCE_TBL_PLAC]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_REGISTRO_USUARIO]'))
ALTER TABLE [dbo].[TBL_REGISTRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_REGI_REFERENCE_TBL_PLAC] FOREIGN KEY([ID_PLACA])
REFERENCES [dbo].[TBL_PLACA] ([ID_PLACA])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_REGI_REFERENCE_TBL_TARJ]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_REGISTRO_USUARIO]'))
ALTER TABLE [dbo].[TBL_REGISTRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_REGI_REFERENCE_TBL_TARJ] FOREIGN KEY([ID_TARJETA])
REFERENCES [dbo].[TBL_TARJETA] ([ID_TARJETA])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_REGI_REFERENCE_TBL_USUA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_REGISTRO_USUARIO]'))
ALTER TABLE [dbo].[TBL_REGISTRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_REGI_REFERENCE_TBL_USUA] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TBL_USUARIOS] ([ID_USUARIO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_TARJ_REFERENCE_TBL_USUA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_TARJETA]'))
ALTER TABLE [dbo].[TBL_TARJETA]  WITH CHECK ADD  CONSTRAINT [FK_TBL_TARJ_REFERENCE_TBL_USUA] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TBL_USUARIOS] ([ID_USUARIO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_SESI_REFERENCE_TBL_CELU]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_SESIONES]'))
ALTER TABLE [dbo].[TBL_SESIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SESI_REFERENCE_TBL_CELU] FOREIGN KEY([ID_CELULAR])
REFERENCES [dbo].[TBL_CELULARES] ([ID_CELULAR])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_SESI_REFERENCE_TBL_USUA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_SESIONES]'))
ALTER TABLE [dbo].[TBL_SESIONES]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SESI_REFERENCE_TBL_USUA] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TBL_USUARIOS] ([ID_USUARIO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TBL_PLAC_REFERENCE_TBL_USUA]') AND parent_object_id = OBJECT_ID(N'[dbo].[TBL_PLACA]'))
ALTER TABLE [dbo].[TBL_PLACA]  WITH CHECK ADD  CONSTRAINT [FK_TBL_PLAC_REFERENCE_TBL_USUA] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[TBL_USUARIOS] ([ID_USUARIO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CarParking_Parking]') AND parent_object_id = OBJECT_ID(N'[dbo].[Vehicle]'))
ALTER TABLE [dbo].[Vehicle]  WITH CHECK ADD  CONSTRAINT [FK_CarParking_Parking] FOREIGN KEY([parking_id])
REFERENCES [dbo].[Parking] ([id])
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[CK_Vehiclestate_66603565]') AND parent_object_id = OBJECT_ID(N'[dbo].[Vehicle]'))
ALTER TABLE [dbo].[Vehicle]  WITH CHECK ADD CHECK  (([state]=(1) OR [state]=(0)))