CREATE TABLE Parking (
  id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NULL,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  updatedAt DATETIME NULL
);

CREATE TABLE Vehicle (
  id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  plate VARCHAR(255) NOT NULL,
  time BIGINT NOT NULL,
  parking VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT GETDATE(),
  updatedAt DATETIME NULL,
  TINYINT NOT NULL  DEFAULT(0) (CHECK (state IN (0,1))
  parking_id INT NOT NULL,
  CONSTRAINT FK_CarParking_Parking FOREIGN KEY (parking_id) REFERENCES Parking(id)
);