apiVersion: apps/v1
kind: Deployment
metadata:
  name: iparking
  labels:
    app: iparking
spec:
  replicas: 1
  template:
    metadata:
      name: iparking
      labels:
        app: iparking
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: app-admin
          image: $DOCKER_IMAGE
          resources:
            limits:
              cpu: 200m
              memory: 150M
            requests:
              cpu: 50m
              memory: 50M
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: iparking-config
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  selector:
    matchLabels:
      app: iparking
