name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Publish Docker image
        run: docker build  --tag ${{ secrets.DOCKERHUB_USERNAME }}/iparking:prod ./src/iParking
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/iparking:latest
